server:
  port: 3032
spring:
  application:
    name: dfpm-usuario-service

  datasource:
    url: jdbc:mysql://localhost:3306/dfpm_usuario
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3030/eureka
  instance:
    hostname: localhost
